version: "3.9"

services:
  database:
    image: postgres:13
    container_name: postgres-container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
